version: '3.8'
services:

  qa-db: # port 5433
    image: postgres:14
    container_name: qa-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432" 
    volumes:
      - qa_db_data:/var/lib/postgresql/data

  qa-web: # port 5001
    build: .
    container_name: qa-web
    environment:
      DB_HOST: qa-db
      DB_PORT: 5432
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - qa-db
    ports:
      - "5001:5000" 

  prod-db: # port 5434
    image: postgres:14
    container_name: prod-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - prod_db_data:/var/lib/postgresql/data

  prod-web:  # port 5002
    build: .
    container_name: prod-web
    environment:
      DB_HOST: prod-db
      DB_PORT: 5432
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - prod-db
    ports:
      - "5002:5000" 

volumes:
  qa_db_data:
  prod_db_data:
