version: '3.8'
services:
  # ---------------------------
  # QA DB
  # ---------------------------
  qa-db:
    image: postgres:14
    container_name: qa-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"    # QA DB 對外連接埠 5433
    volumes:
      - qa_db_data:/var/lib/postgresql/data

  # ---------------------------
  # QA Web (Flask + Flyway)
  # ---------------------------
  qa-web:
    build: .
    container_name: qa-web
    environment:
      DB_HOST: qa-db
      DB_PORT: 5432
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - qa-db
    ports:
      - "5001:5000"    # QA Web 對外連接埠 5001

  # ---------------------------
  # Production DB
  # ---------------------------
  prod-db:
    image: postgres:14
    container_name: prod-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"   # 線上DB 對外連接埠 5434
    volumes:
      - prod_db_data:/var/lib/postgresql/data

  # ---------------------------
  # Production Web (Flask + Flyway)
  # ---------------------------
  prod-web:
    build: .
    container_name: prod-web
    environment:
      DB_HOST: prod-db
      DB_PORT: 5432
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    depends_on:
      - prod-db
    ports:
      - "5002:5000"   # 線上Web 對外連接埠 5002

volumes:
  qa_db_data:
  prod_db_data:
